# Generated by Django 3.2.16 on 2023-03-09 21:50

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True, verbose_name='Дата удаления')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание книги')),
            ],
            options={
                'verbose_name': 'Книга',
                'verbose_name_plural': 'Книги',
                'db_table': 'books',
            },
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True, verbose_name='Дата удаления')),
                ('number', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(10000)], verbose_name='Номер главы')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание главы')),
                ('book_part', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(10000)], verbose_name='Часть книги')),
                ('summary', models.TextField(blank=True, null=True, verbose_name='Краткое содержание главы')),
                ('interpretation', models.TextField(blank=True, null=True, verbose_name='Интерпретация')),
                ('image', models.ImageField(blank=True, null=True, upload_to='chapters/', verbose_name='Картинка')),
                ('book', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chapters', to='wiki.book', verbose_name='Книга')),
            ],
            options={
                'verbose_name': 'Глава',
                'verbose_name_plural': 'Главы',
                'db_table': 'chapters',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True, verbose_name='Дата удаления')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('comment_text', models.TextField(verbose_name='Текст примечания')),
                ('image', models.ImageField(blank=True, null=True, upload_to='comments/', verbose_name='Картинка')),
                ('page_number_by_2012', models.PositiveIntegerField(verbose_name='Нумерация глав в старом издании')),
                ('page_number_by_2021', models.PositiveIntegerField(verbose_name='Нумерация глав в новом издании')),
                ('sort', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='Сортировка')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('book', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comments', to='wiki.book', verbose_name='Книга')),
                ('chapter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comments', to='wiki.chapter', verbose_name='Номер главы')),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Комментарии',
                'db_table': 'comments',
                'ordering': ('page_number_by_2012', 'sort'),
            },
        ),
        migrations.CreateModel(
            name='TableChronology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True, verbose_name='Дата удаления')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Дата')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Событие')),
                ('sort', models.PositiveBigIntegerField(verbose_name='Сортировка')),
            ],
            options={
                'verbose_name': 'Строка таблицы хронологии',
                'verbose_name_plural': 'Строки таблицы хронологии',
                'db_table': 'chronologies',
                'ordering': ('sort',),
            },
        ),
        migrations.CreateModel(
            name='CommentLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True, verbose_name='Дата удаления')),
                ('link', models.URLField(blank=True, null=True, verbose_name='Ссылка к комментарию')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='wiki.comment', verbose_name='Комментарий')),
            ],
            options={
                'verbose_name': 'Ссылка к примечанию',
                'verbose_name_plural': 'Ссылки к примечанию',
                'db_table': 'comment_links',
            },
        ),
        migrations.CreateModel(
            name='ChapterLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True, verbose_name='Дата удаления')),
                ('link', models.URLField(blank=True, null=True, verbose_name='Ссылка к главе')),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='wiki.chapter', verbose_name='Глава')),
            ],
            options={
                'verbose_name': 'Ссылка к главе',
                'verbose_name_plural': 'Ссылки к главе',
                'db_table': 'chapter_links',
            },
        ),
    ]
