# Generated by Django 3.2.16 on 2023-03-18 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='number',
            field=models.CharField(max_length=8, verbose_name='Номер главы'),
        ),
    ]
