# Generated by Django 2.2.19 on 2022-10-08 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'verbose_name': 'Книга', 'verbose_name_plural': 'Книги'},
        ),
        migrations.AlterModelOptions(
            name='chapter',
            options={'verbose_name': 'Глава', 'verbose_name_plural': 'Главы'},
        ),
        migrations.AlterField(
            model_name='comment',
            name='book',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comments', to='wiki.Book', verbose_name='Книга'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='order_number',
            field=models.DecimalField(decimal_places=3, max_digits=5),
        ),
    ]
