# Generated by Django 3.2.16 on 2023-06-30 18:16

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wiki', '0002_alter_chapter_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tablechronology',
            name='date',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='tablechronology',
            name='sort',
            field=models.CharField(max_length=10, verbose_name='Сортировка'),
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True, verbose_name='Дата удаления')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('text', ckeditor.fields.RichTextField(verbose_name='Текст статьи')),
                ('image', models.ImageField(blank=True, null=True, upload_to='articles/', verbose_name='Картинка')),
                ('chapter', models.IntegerField(verbose_name='Номер раздела')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to=settings.AUTH_USER_MODEL, verbose_name='Автор статьи')),
            ],
            options={
                'verbose_name': 'Статья',
                'verbose_name_plural': 'Статьи',
                'db_table': 'articles',
            },
        ),
    ]
