# Generated by Django 3.2.16 on 2023-07-09 08:05

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0003_auto_20230630_2116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Описание главы'),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='interpretation',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Интерпретация'),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='summary',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Краткое содержание главы'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment_text',
            field=ckeditor.fields.RichTextField(verbose_name='Текст примечания'),
        ),
    ]
