# Generated by Django 2.2.19 on 2022-10-08 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0003_auto_20221008_1536'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='page_number',
            new_name='page_number_by_2012',
        ),
        migrations.AddField(
            model_name='comment',
            name='page_number_by_2021',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
