# Generated by Django 3.2.16 on 2023-07-09 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0004_auto_20230709_1105'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='pages',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Номер страниц'),
        ),
    ]
