# Generated by Django 3.2.16 on 2023-07-13 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0005_chapter_pages'),
    ]

    operations = [
        migrations.CreateModel(
            name='CircleTableCharacters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True, verbose_name='Дата удаления')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Круг в таблице персонажей',
                'verbose_name_plural': 'Круги в таблице персонажей',
                'db_table': 'circles',
            },
        ),
        migrations.CreateModel(
            name='TableСharacters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True, verbose_name='Дата удаления')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('value_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Имя в оригинале и значение')),
                ('characteristics', models.TextField(blank=True, null=True, verbose_name='Характеристика')),
                ('portrait', models.TextField(blank=True, null=True, verbose_name='Портрет')),
                ('groups', models.TextField(blank=True, null=True, verbose_name='Группы')),
                ('mentions', models.TextField(verbose_name='Упоминания')),
                ('circle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characters', to='wiki.circletablecharacters', verbose_name='Круг персонажа')),
            ],
            options={
                'verbose_name': 'Запись в таблице персонажей',
                'verbose_name_plural': 'Записи в таблице персонажей',
                'db_table': 'characters',
            },
        ),
    ]
