# Generated by Django 3.2.16 on 2023-07-13 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0006_circletablecharacters_tableсharacters'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tableсharacters',
            name='value_name',
            field=models.TextField(blank=True, null=True, verbose_name='Имя в оригинале и значение'),
        ),
    ]
