# Generated by Django 2.2.19 on 2022-10-08 18:23

from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0007_auto_20221008_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='image',
            field=sorl.thumbnail.fields.ImageField(blank=True, null=True, upload_to='comments/', verbose_name='Картинка'),
        ),
    ]
