# Generated by Django 3.2.16 on 2023-09-09 17:44

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0008_auto_20230830_0113'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ('sort',), 'verbose_name': 'Статья', 'verbose_name_plural': 'Статьи'},
        ),
        migrations.AddField(
            model_name='chapter',
            name='pov',
            field=ckeditor.fields.RichTextField(default='pov', verbose_name='POV'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='article',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Название'),
        ),
    ]
