# Generated by Django 2.2.19 on 2022-10-08 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0009_auto_20221008_1914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='order_number',
            field=models.IntegerField(),
        ),
    ]
