# Generated by Django 2.2.19 on 2022-10-09 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0010_auto_20221008_1940'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='interpretation',
            field=models.TextField(blank=True, null=True, verbose_name='Интерпретация'),
        ),
        migrations.AddField(
            model_name='chapter',
            name='summary',
            field=models.TextField(blank=True, null=True, verbose_name='Краткое содержание главы'),
        ),
    ]
