# Generated by Django 3.2.16 on 2023-10-07 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0010_tablechronology_event_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='author_article',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Автор статьи'),
        ),
        migrations.AlterField(
            model_name='article',
            name='attitude',
            field=models.TextField(choices=[('Другое', 'Другое'), ('Раздел 1', 'Раздел 1'), ('Раздел 1 (статья 1)', 'Раздел 1 (статья 1)'), ('Раздел 1 (статья 2)', 'Раздел 1 (статья 2)'), ('Раздел 2', 'Раздел 2'), ('Раздел 3', 'Раздел 3'), ('Раздел 4', 'Раздел 4'), ('Раздел 5', 'Раздел 5'), ('Раздел 6', 'Раздел 6'), ('Раздел 7', 'Раздел 7'), ('Авторы', 'Авторы'), ('Томас Пинчон', 'Томас Пинчон'), ('Запланированные мероприятия', 'Запланированные мероприятия'), ('Записи встреч', 'Записи встреч'), ('Другие книги', 'Другие книги')], verbose_name='Отношение к разделу'),
        ),
    ]
