# Generated by Django 2.2.19 on 2022-10-09 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0011_auto_20221009_0804'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание главы'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment_text',
            field=models.TextField(verbose_name='Текст примечания'),
        ),
    ]
