# Generated by Django 3.2.16 on 2023-11-14 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0012_alter_article_attitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='comment_link',
            field=models.IntegerField(blank=True, null=True, verbose_name='Cвязь с другим примечанием'),
        ),
    ]
