# Generated by Django 3.2.16 on 2023-12-15 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0013_comment_comment_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='circletablecharacters',
            name='book',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='characters', to='wiki.book', verbose_name='Книга'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tablechronology',
            name='book',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='chronology', to='wiki.book', verbose_name='Книга'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='article',
            name='attitude',
            field=models.TextField(choices=[('Другое', 'Другое'), ('Раздел 1', 'Раздел 1'), ('V Раздел 1', 'V Раздел 1'), ('Раздел 4', 'Раздел 4'), ('V Раздел 4', 'V Раздел 4'), ('V Раздел 5', 'V Раздел 5'), ('Раздел 1 (статья 1)', 'Раздел 1 (статья 1)'), ('V Раздел 1 (статья 1)', 'V Раздел 1 (статья 1)'), ('Раздел 1 (статья 2)', 'Раздел 1 (статья 2)'), ('V Раздел 1 (статья 2)', 'V Раздел 1 (статья 2)'), ('Раздел 5', 'Раздел 5'), ('Раздел 7', 'Раздел 7'), ('Авторы', 'Авторы'), ('Томас Пинчон', 'Томас Пинчон'), ('Запланированные мероприятия', 'Запланированные мероприятия'), ('Записи встреч', 'Записи встреч'), ('Другие книги', 'Другие книги'), ('О сайте', 'О сайте')], verbose_name='Отношение к разделу'),
        ),
    ]
