# Generated by Django 2.2.19 on 2022-10-09 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0013_chapter_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='book_part',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
