# Generated by Django 2.2.19 on 2022-10-09 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0014_chapter_book_part'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='links',
            field=models.TextField(blank=True, null=True, verbose_name='Ссылки к примечанию'),
        ),
    ]
