# Generated by Django 3.2.16 on 2023-12-18 13:00

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0014_auto_20231215_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='pov',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='POV'),
        ),
    ]
