# Generated by Django 2.2.19 on 2022-10-09 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0015_comment_links'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='links',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Ссылки к примечанию'),
        ),
    ]
