# Generated by Django 3.2.16 on 2023-12-18 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0016_alter_comment_page_number_by_2021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='page_number_by_2012',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Нумерация глав в старом издании'),
        ),
    ]
