# Generated by Django 2.2.19 on 2022-10-09 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0016_auto_20221009_1707'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='links',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Ссылки к главе'),
        ),
    ]
