# Generated by Django 3.2.16 on 2024-02-05 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0018_chapter_sort'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tablechronology',
            name='sort',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Сортировка'),
        ),
    ]
