# Generated by Django 2.2.19 on 2022-10-31 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0018_tablechronology'),
    ]

    operations = [
        migrations.AddField(
            model_name='tablechronology',
            name='order_number',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
