# Generated by Django 2.2.19 on 2022-10-31 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0019_tablechronology_order_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tablechronology',
            options={'ordering': ['order_number'], 'verbose_name': 'Строка таблицы хронологии', 'verbose_name_plural': 'Строки таблицы хронологии'},
        ),
        migrations.AlterField(
            model_name='tablechronology',
            name='order_number',
            field=models.CharField(max_length=3),
        ),
    ]
