# Generated by Django 3.2.16 on 2024-02-05 20:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0019_alter_tablechronology_sort'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tablechronology',
            name='book',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chronology', to='wiki.book', verbose_name='Книга'),
        ),
    ]
