# Generated by Django 2.2.19 on 2022-10-31 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0020_auto_20221031_1144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tablechronology',
            name='date',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='tablechronology',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Событие'),
        ),
    ]
