# Generated by Django 3.2.16 on 2024-04-05 20:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0021_alter_article_attitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='book_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='wiki.book', verbose_name='Книга'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tableсharacters',
            name='book_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='characters', to='wiki.book', verbose_name='Книга'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='circletablecharacters',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='circles', to='wiki.book', verbose_name='Книга'),
        ),
    ]
