# Generated by Django 2.2.19 on 2022-11-01 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0021_auto_20221031_1225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tablechronology',
            name='order_number',
            field=models.CharField(max_length=10),
        ),
    ]
