# Generated by Django 3.2.16 on 2024-04-09 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0023_alter_tableсharacters_book_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tableсharacters',
            old_name='book_id',
            new_name='book',
        ),
    ]
