version: '3.8'
services:
  db:
    image: postgres:13.0-alpine
    volumes:
      - ./data/postgres:/var/lib/postgresql/data/
    env_file:
      - ./.env
    container_name: pynchon-db

  backend:
    build:
      context: ../pynchon_wiki/
      dockerfile: Dockerfile
    volumes:
      - ../pynchon_wiki/media/:/app/media/
      - ../pynchon_wiki/logs:/app/logs
    depends_on:
      - db
    env_file:
      - ./.env
    restart: always
    container_name: pynchon-backend

  nginx:
    image: nginx:1.19.3
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../pynchon_wiki/static/:/var/html/static/
      - ../pynchon_wiki/media/:/var/html/media/
    depends_on:
      - backend
    container_name: pynchon-nginx
