# Generated by Django 3.2.16 on 2023-04-03 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TopMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True, verbose_name='Дата удаления')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('url', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ссылка на страницу')),
                ('auth_only', models.BooleanField(default=False, verbose_name='Только для авторизованных')),
                ('sort', models.PositiveSmallIntegerField(default=100, verbose_name='Сортировка')),
            ],
            options={
                'verbose_name': 'Меню',
                'verbose_name_plural': 'Меню',
                'db_table': 'menus',
            },
        ),
    ]
